### ISSUE TITLE
Improve paste function of multiple lines

### ISSUE THREAD

**Issue by hata6502** [codex-team/editor.js#1015]
Paste multiple lines text: 

![スクリーンショット 2020-01-17 19 00 17](https://user-images.githubusercontent.com/7702653/72603098-bd5cbc80-395b-11ea-864a-e28b825cfb94.png)

Then, text is pasted as **other blocks**. 
![スクリーンショット 2020-01-17 19 00 32](https://user-images.githubusercontent.com/7702653/72603314-23494400-395c-11ea-81a9-b718f2cbc962.png)

I expected that text is pasted in **same block**. 
And I think that it is more useful!
![スクリーンショット 2020-01-17 19 00 56](https://user-images.githubusercontent.com/7702653/72603294-188eaf00-395c-11ea-9573-756d67a773ad.png)

**Comment by neSpecc** [comment]
I think, that current behaviour is more suitable. We prefer concept "One paragraph = one block", because it is block-style editor, so you able to perform some manupulations with separated blocks. Having line breaks inside one block is more like an exception for rare use cases.

Can you describe your use case, when you need a several `<p>` inside one Paragrapg block?

**Comment by hata6502** [comment]
I agree "One paragraph = one block" concept, too! 
But, I feel unnatural that paste result is different from copied text.

**Comment by skanehira** [comment]
> I feel unnatural that paste result is different from copied text.
> I think that one Paragraph block shouldn't contain multiple <p>, but my case is <br>, not <p>

I’m agree this too.
