### ISSUE TITLE
Image tool not appearing on toolbar in example.html

### ISSUE THREAD

**Issue by tyazeez** [codex-team/editor.js#1160]
Why is the image tool not showing on the toolbar in example.html but shows on the editorjs.io demo page?

I noticed this while trying to set the editor up using the example.html page as a guide. All other initialized tools like the header, list, quote, warning etc. all successfully appeared on the toolbar.

**Comment by neSpecc** [comment]
That's because the example.html does not have a backend uploader, so it uses the [Simple Image](http://github.com/editor-js/simple-image) tool instead of [Image Tool](http://github.com/editor-js/image).

Simple Image tool provides image blocks by pasting image URLs into empty paragraphs. So it does not appear in a Toolbox.
