### ISSUE TITLE
[Bug]  Back Space Deleting Whole block content  

### ISSUE THREAD

**Issue by md-haroon** [codex-team/editor.js#1204]
Deleting Whole content of current block automatically when i single press of backspace
 
![image](https://user-images.githubusercontent.com/16242328/84742249-cae9a180-afe2-11ea-9b62-2c0fa87a23e7.png)

Also you can see in above screenshot , "codex-editor--empty" class exists even the content exist , 

Reason for this error  **Microsoft editor** extension , if you installed this extension you will face this issues

**Comment by ranemihir** [comment]
There's no such behaviour observed. 

**Clicking on the content once and pressing backspace only deletes that particular character.**

The content of the block gets deleted **on double clicking** on it and then pressing backspace; which is expected behaviour. 

Also, the whole block gets deleted only when it is selected by clicking on the **click to tune icon** and then pressing backspace; which is also expected behaviour.

**Comment by ranemihir** [comment]
The claim about **codex-editor--empty** class to exist even after inserting content is false.

**Comment by ranemihir** [comment]
If you can provide more info about the issue we will reopen it but for now we are closing it as the issue does not seem to exist.

**Comment by milkmanjr** [comment]
I'm able to reproduce this issue. When the **.ms-editor-squiggler** div is after the **ce-paragraph** div, a backspace deletes all the content in that block.
