### ISSUE TITLE
blocks.insert API does not pass config parameter to Tool

### ISSUE THREAD

**Issue by dmtstr** [codex-team/editor.js#1230]
Describe a bug:
`blocks.insert` API does not pass `config` parameter to Tool

Steps to reproduce:
1. Open **insert** method docs (https://editorjs.io/blocks#insert)
2. Call insert **method** with the third parameter (config)
3. Tool receives an empty config object

Expected behavior:
Config is passed to Tool constructor

_Editor.js 2.18.0_

Code sample
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@2.18"></script>
</head>
<body>

    <div id="editorjs"></div>

    <script>

        class Test {

            constructor ({config}) {
                console.log(config.foo); // undefined
            }

            render () {
                return document.createElement('div');
            }

        }

        const editor = new EditorJS({
            tools: {
                test: Test
            }
        });

        editor.isReady.then(() => {
            editor.blocks.insert('test', {}, {foo: 'bar'})
        })

    </script>

</body>
</html>
```

**Comment by ranemihir** [comment]
@karpovsystems Can you specify any particular use case in which a tool would require the entire `config` property?

**Comment by ranemihir** [comment]
@karpovsystems What is the purpose of sending the `config` parameter through the `blocks.insert` method? How is sending the `config` parameter to the tool's constructor being currently implemented?

**Comment by karpovsystems** [comment]
> What is the purpose of sending the `config` parameter through the `blocks.insert` method?

In my case, it would determine whether the block was created by the user or programmatically.

> How is sending the config parameter to the tool's constructor being currently implemented?

I'm not quite clear what you mean, but it's possible to send the `config` parameter via configuration object https://editorjs.io/provide-custom-configuration

```javascript
class Test {

    constructor ({config}) {
        console.log(config.foo); // bar
    }

    render () {
        return document.createElement('div');
    }

}

const editor = new EditorJS({
    tools: {
        test: {
            class: Test,
            config: {foo: 'bar'} // passing config data
        }
    },
    data: {
        blocks: [{
            type: 'test'
        }]
    }
});
```

**Comment by ranemihir** [comment]
@karpovsystems Can you explain a proper use case?

**Comment by karpovsystems** [comment]
@ranemihir check [Header](https://github.com/editor-js/header), [Image](https://github.com/editor-js/image), [Embed](https://github.com/editor-js/embed), [Quote](https://github.com/editor-js/quote), [Link](https://github.com/editor-js/link) tools. All of them use the `config` parameter

**Comment by ranemihir** [comment]
@karpovsystems I know these tools require the `config` object and is being sent to their respective constructors. But in exactly what context these plugins will be required to send it through `blocks.insert` method?

**Comment by karpovsystems** [comment]
Let's say you have a button, clicking on which should add Header and Image blocks.

**Comment by neSpecc** [comment]
Agree with @ranemihir. 

The `config` property of the Tool constructor params it is the list of options supported by the Tool. They are specified once by the Editor Config. And they are the same through the all blocks of this Tool.

In the attached PR the `config` is used like an "additional data" and the meaned like they can be different between several blocks of this Tool. 

So if there is only use case of determining whether the block was created by API or not, we can think more logical solution.

@karpovsystems  Can you describe why exactly you need to know whether the block was created by API or by Editor core?

Also, there is a little issue:

1. We need to remove `config` param from the `block.insert()` method, because it was added there by a mistake.

**Comment by karpovsystems** [comment]
> Can you describe why exactly you need to know whether the block was created by API or by Editor core?

I worked on a [spoiler](https://quirky-swartz-317498.netlify.app/example/) tool. It appends two blocks: spoiler start & spoiler end. Blocks between start & end are spoiler content.
End block is created programmatically, and I needed some flag for detecting that. Since `block.insert()` didn't work, I put this flag to the `data` object and created this issue.

I don't mind removing `config` from `block.insert()`.

__

**Comment by ranemihir** [comment]
@karpovsystems I can't think of a practical use case of the tool. This needs more discussion.

**Comment by sos-productions** [comment]
@karpovsystems I think spoiler feature as a container of blocks would be a great idea. For exemple you edit an html page and you want to edit the title of html page. This does not belong to the visble part of the page as it is its attributes generally  stored in the head of html .For now I lay out this as an extra paragraph that can be easily wrongly mixed on block move with content of the page on edit.This is because blocks have not move constraints for now. Of course I can decide to have separate inline editor for each group of blocks to prevent this but this bring multiple editorjs complexity management!

**Comment by neSpecc** [comment]
Closed as won't change.
