### ISSUE TITLE
can not correct parse tag of <table> with renderFromHTML [Bug]

### ISSUE THREAD

**Issue by qqqays** [codex-team/editor.js#1288]
Describe a bug.

config：
`tools:{
table:Table
}`

code：
`editor.blocks.renderFromHTML('<table border="1">\n<tr>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n</tr>\n<tr>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n</tr>\n<tr>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n<td>fdfsfsd</td>\n</tr>\n</table>')`

Expected behavior: table block

like this: 
![image](https://user-images.githubusercontent.com/22659021/91519368-037ff280-e925-11ea-9176-8a643ce812b9.png)

result Screenshots: 
![image](https://user-images.githubusercontent.com/22659021/91519225-953b3000-e924-11ea-915b-43e3c99e2ad6.png)

Device, Browser, OS: window10, chrome

Editor.js version: latest

Plugins you use with their versions: latest

**Comment by neSpecc** [comment]
It is not recommended to use undocumented method `renderFromHTML` for creating EditorJS format from HTML. It supports only the simplest cases.

Anyway, you can improve the [Table](https://github.com/editor-js/table) tool by adding the `pasteConfig` and the `onPaste` methods. [Example](https://editorjs.io/paste-substitutions). And this issue is better to create at the [Table](https://github.com/editor-js/table/issues) tool repo
