### ISSUE TITLE
[Bug] toolbar icon overflow on small screens

### ISSUE THREAD

**Issue by oldrich-s** [codex-team/editor.js#1388]
The toolbar icons overflow badly on iPhone

Screenshots:

![3CC06DB7-FDCD-40C7-898A-A87F08C2E1A4](https://user-images.githubusercontent.com/37391/96496621-bac02800-1249-11eb-909a-c14fbc5f39ce.png)

Device, Browser, OS:

iPhone 11, iOS 14

Editor.js version:

Plugins you use with their versions:

**Comment by itsmingjie** [comment]
Hi! I'm one of the program coordinators of a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution. 

We'll claim this issue for now and a group of students will be on it soon with mentorship! If this issue is no longer relevant, please let me know.

**Comment by nbrown1337** [comment]
It appears this issue has been fixed when running local dev version. It is **not** fixed on the edititorjs.io website though.

**Comment by robonetphy** [comment]
Hey @oldrich-s, Thanks for the issue. But in version - 2.24.0 - The Toolbox became vertical due to which this issue is not applicable. so I am closing this issue.
