### ISSUE TITLE
[Bug] menu sign not displaying properly

### ISSUE THREAD

**Issue by 0xdud** [codex-team/editor.js#1423]
The + sign for the menu not working properly

Steps to reproduce:
1.When I resize the browser at 1138px / 844px the + sign enters the input 

Expected behavior:

Screenshots:
![image](https://user-images.githubusercontent.com/60102048/98805220-eafd7f80-241f-11eb-83cd-bd181811cc25.png)

Device, Browser, OS:
Desktop, Chrome Version 86.0.4240.183 (Official Build) (64-bit), Windows
Editor's version:
2.18.0

Plugins you use with their versions:

**Comment by ilyapoz** [comment]
I experience the same issue when I initialize editor.js in a hidden tab of material-ui tabbed control, but this bugreport seems easier to reproduce

**Comment by ilyapoz** [comment]
Still reproduced in next. Can you please look into it, very annoying and basic functionality.

**Comment by neSpecc** [comment]
Looks like you are inserting Editor at the container which is less that a single block content width. Editor.js [handles](https://github.com/codex-team/editor.js/blob/next/src/components/modules/ui.ts#L292-L297) such cases enabling the `Narrow Mode` where the Plus button places inside the Block (because there is no space outside)
