### ISSUE TITLE
Clearing tags inside <a> if it's inside <p>

### ISSUE THREAD

**Issue by deniskarpenko** [codex-team/editor.js#1633]
Hello.
When pasting html <p.. > <a ..> <img src = "image.jpeg" </a> </p>. All objects inside <a> are cleaned if it is a child of <p>. Is there any way to avoid this?

**Comment by gohabereg** [comment]
Hi @deniskarpenko 
It might be related to the bug #1630 which is fixed in v2.20.1. In general, sanitizer config is composed of Tool sanitizer config and configs of Inline Toole your Tool uses.

But if you are trying to paste following markup
```
<p>
  <a>
    <img />
  </a>
</p>
```

it won't be parsed correctly because Image Tool expects only the image tag, not the anchor.

**Comment by deniskarpenko** [comment]
Thanks for the answer

**Comment by JoeWoodward** [comment]
I think this is actually related to the HTMLJanitor logic. I've just been debugging another issue I've been having and noticed this logic 

https://github.com/guardian/html-janitor/blob/master/src/html-janitor.js#L32
https://github.com/guardian/html-janitor/blob/97f27765f95dc912476a7cac9b06036a310d7846/src/html-janitor.js#L89

I also found a bug with tables that is related to this issue. IMO this sanitizer library should be removed and switched out for something with better options/tests
