### ISSUE TITLE
[Bug] TypeError: t.some is not a function

### ISSUE THREAD

**Issue by abdessamadely** [codex-team/editor.js#1750]
When adding CodeTool `@editorjs/code`, It does cause this bug
I used the example from [editorjs.io](https://editorjs.io/) homepage

Steps to reproduce:
1. Go to [editorjs.io](https://editorjs.io/) homepage
2. Open the console
3. Create a new Code block
4. Write something
5. You should see the error on the console

Expected behavior: To not throw this error

Screenshots:

![TypeError: t.some is not a function screenshot](https://i.imgur.com/ZHuHjvF.png)

Device, Browser, OS: Macbook pro, Chrome, Mac os Big Sur

Editor.js version: "^2.22.2"

Plugins you use with their versions:
`"@editorjs/code": "^2.7.0"`

**Comment by Ivanezko** [comment]
Same here. Had to rollback to 2.19.3 in a while.

**Comment by abdessamadely** [comment]
> Same here. Had to rollback to 2.19.3 in a while.

Thanks, I was looking for a version to rollback, I'll try it out 🙏.

**Comment by nishalk01** [comment]
Thanks Ivanezko,That worked

**Comment by corund** [comment]
Same Occurs in "The first plugin" example. I think it would occur when plugin has input field, and type-in there.

**Comment by khanakia** [comment]
The issue is still there in `2.25.0`. The issue occurs when I select values from input autocomplete

<img width="630" alt="Screenshot 2022-07-24 at 11 07 40 AM" src="https://user-images.githubusercontent.com/2174170/180633813-6b814567-dbb2-40b7-b722-f9d13d06b59e.png">
<img width="1382" alt="Screenshot 2022-07-24 at 11 07 50 AM" src="https://user-images.githubusercontent.com/2174170/180633820-88f14014-7b2e-4f5e-ae7a-37ed5a4e5819.png">
