### ISSUE TITLE
Define new "block-updated" event. 

### ISSUE THREAD

**Issue by krisnik** [codex-team/editor.js#2221]
The question.

> How to differentiate Block Update (vs) Block insert / delete. 

Why and how the question has come up.

When block is updated using `block.update(id, BlockToolData)` - EditorJS `onChange` api gets called twice. once with `blocked-removed` and later with `block-added` events. 

`block-removed` and `block-added` events are also fired when the blocks are deleted / added to the EditorJS instance. 

Hence, from the onChange response, it is not possible to differentiate if block's content is updated or a new block is added / existing block is removed.

**Comment by lijie1129** [comment]
I think this is because the `update` function is implemented by calling the `insert` function and specifying the `replace` parameter as `true`. 

Therefore, there are two final actions: 

* delete the old block
* insert the block holding the new data in the original location.

This is why an update causes the `onChange` API gets called twice.


**_This is the definition of the update function:_**
https://github.com/codex-team/editor.js/blob/870e265af0e2114c0a1504a70148ea3c5e28d959/src/components/modules/api/blocks.ts#L291-L311

**_This is the definition of the insert function:_**
https://github.com/codex-team/editor.js/blob/870e265af0e2114c0a1504a70148ea3c5e28d959/src/components/modules/blockManager.ts#L266-L322


It seems that the simple way is:

1. Provide a new function in the **_blockManager.ts_** file to update the block's data according to the specified block ID. (This function locates the correct block in `this._blocks` by ID and directly replace it.)
2. Then, directly call the new function defined above in the update function of the **_api/blocks.ts_** file.
3.  Finally, trigger the `onChange` API once.

**Comment by lijie1129** [comment]
## Why does it need to support a single event

Recently, I tried to make a binding between the [YJS](https://github.com/yjs/yjs) and EditorJS.

This is to realize an idea. Please refer to [here](https://discuss.yjs.dev/t/editor-js-bindings/1349/5?u=jarone).

### First
Since the synchronization EditorJS changes to the data model (YJS doc) is triggered by `onChange`.

It is necessary to minimize unnecessary events and avoid performance waste.

### Second
In the scenario of multi-person collaborative editing, directly removing and replacing the DOM of the entire block will cause the collaborator to lose the input focus, which will cause experience problems. 

Therefore, it is a good way to delegate the work of updating a specific block content to a specific plug-in.

**Comment by lijie1129** [comment]
> ## Why does it need to support a single event
> 
> 
> 
> Recently, I tried to make a binding between the [YJS](https://github.com/yjs/yjs) and EditorJS.
> 
> 
> 
> This is to realize an idea. Please refer to [here](https://discuss.yjs.dev/t/editor-js-bindings/1349/5?u=jarone).
> 
> 
> 
> ### First
> 
> Since the synchronization EditorJS changes to the data model (YJS doc) is triggered by `onChange`.
> 
> 
> 
> It is necessary to minimize unnecessary events and avoid performance waste.
> 
> 
> 
> ### Second
> 
> In the scenario of multi-person collaborative editing, directly removing and replacing the DOM of the entire block will cause the collaborator to lose the input focus, which will cause experience problems. 
> 
> 
> 
> Therefore, it is a good way to delegate the work of updating a specific block content to a specific plug-in.
> 
> 

Good job! @neSpecc

This issue has been resolved. 

So my work can be continue.

https://github.com/codex-team/editor.js/commit/922dfd8741db26e599ed9c67e07d7272c03ac2e4

**Comment by krisnik** [comment]
Thank you for the fix @neSpecc . Marking as resolved.
