### ISSUE TITLE
InlineToolbar incorrectly overflows on right edge

### ISSUE THREAD

**Issue by SneakiBrina** [codex-team/editor.js#2476]
When a parent of the editor is using position: fixed or absolute, the inline toolbar will overflow on the right side.

Expected behaviour:
Inline toolbar should position itself to avoid right-side overflow if there is space.

Screenshots:
![image](https://github.com/codex-team/editor.js/assets/57508183/d4331be6-ca30-43e1-a663-b583ccf81fca)

Device, Browser, OS: Desktop, Chrome, Windows 10

Editor.js version: 2.28.0

**Comment by lijie1129** [comment]
hi, @SneakiBrina 

Thank you for reporting this issue. 🤝

To fix this issue, I think we need to get the width value of the inline toolbar.

The current rendering process of inline toolbar is as follows:

1. Calculate the positioning information of the inline toolbar
2. Display inline toolbar (transparency adjusted from 0 to 1)
3. Fill the inline toolbar with inline action buttons, such as bold, italic...

https://github.com/codex-team/editor.js/blob/next/src/components/modules/toolbar/inline.ts#L155-L156

https://github.com/codex-team/editor.js/blob/next/src/components/modules/toolbar/inline.ts#L167

Since the third step will affect the width value of the inline toolbar, we need to calculate the positioning information after the third step (the issue of overflow on the right side is handled in the logic of calculating the positioning information)

**Comment by lijie1129** [comment]
> hi, @SneakiBrina
> 
> Thank you for reporting this issue. 🤝
> 
> To fix this issue, I think we need to get the width value of the inline toolbar.
> 
> The current rendering process of inline toolbar is as follows:
> 
> 1. Calculate the positioning information of the inline toolbar
> 2. Display inline toolbar (transparency adjusted from 0 to 1)
> 3. Fill the inline toolbar with inline action buttons, such as bold, italic...
> 
> https://github.com/codex-team/editor.js/blob/next/src/components/modules/toolbar/inline.ts#L155-L156
> 
> https://github.com/codex-team/editor.js/blob/next/src/components/modules/toolbar/inline.ts#L167
> 
> Since the third step will affect the width value of the inline toolbar, we need to calculate the positioning information after the third step (the issue of overflow on the right side is handled in the logic of calculating the positioning information)

hi, @SneakiBrina 

I saw the PR you submitted. It seems that your solution is correct. 👍

Please ignore what I said above.

**Comment by MussaratAziz** [comment]
@SneakiBrina  any way to change the icons on InlineToolbar?

**Comment by neSpecc** [comment]
Resolved by #2550
