### ISSUE TITLE
Divide blocks into container blocks and leaf blocks

### ISSUE THREAD

**Issue by LinFeng1997** [codex-team/editor.js#803]
Editor.js is an awesome project, both in design and implementation.

But I need to nesting a block in other block.

So I hope that you can divide blocks into container blocks and leaf blocks.

**Comment by emredipi** [comment]
Exactly, that's what I need too. The editor needs to have bootstrap "raw" and "col" structure. (This is just example of course. In fact, it will be children-parent-sibling relationship in json)

**Comment by LinFeng1997** [comment]
@emredipi Yes!Such as Insert a Image to a paragraph.

**Comment by n0str** [comment]
You can create your own tool for a paragraph with a nested image. EditorJS [allows that](https://editorjs.io/creating-a-block-tool)

**Comment by tom-sherman** [comment]
I'm trying to create a general nested block plugin, would the best way to this be to nest instances of Editor instances?

So if I wanted a two column layout block for example, my tool could spawn two new Editor instances and place them side by side?

**Comment by enes-sahin** [comment]
> So if I wanted a two column layout block for example, my tool could spawn two new Editor instances and place them side by side?

@tom-sherman I think multiple Editor instances is not very effective for two column layout. Maybe you could try `column-count` property in CSS.

![column-count](https://user-images.githubusercontent.com/25066964/64691812-4a6aa300-d49c-11e9-9973-7d505de4ac6b.png)

**Comment by tom-sherman** [comment]
@enes-sahin This doesn't support the experience I'm after. I'm building a Squarespace-like layout builde, where I can configure rows and columns

**Comment by enes-sahin** [comment]
@tom-sherman What i undestand from your comment is that you try to create page builder/layout builder like popular layout plugins used especially in wordpress. 

First thing that comes to mind is that create your own tool and create new ```type``` field in ***Block data***

```js
const editor = new EditorJs({ 
  tools: { 
   row: Row, 
   column: Column 
  }, 
})
```
Output will be like : 
```js
{
   "time": 1550476186479,
   "blocks": [
      {
         "type": "row",
         "data": {
            "text": "",
         }
      },
      {
         "type": "column",
         "data": {
            "text": "Some text"
         }
      },
      {
         "type": "column",
         "data": {
            "text": "Some text",
         }
      }
   ],
   "version": "2.8.1"
}
```
But the problem is that **there is no unique id for blocks**, so It is very difficult to determine which column/row is related to another column/row. 

Issues about unique id for blocks https://github.com/codex-team/editor.js/issues/727 and https://github.com/codex-team/editor.js/issues/873

As for nesting, i am not sure if it is allowed in Editor.js or not. Maybe you can use multiple instances but for every row/column/etc, but it would be difficult to maintain.

**Comment by matias-miranda** [comment]
hey @tom-sherman were you able to do it, I'm facing the exactly same scenario

**Comment by tom-sherman** [comment]
@matias-miranda unfortunately not, I ended up going with a different library (GrapesJS) as the base for the application I'm building.

**Comment by hata6502** [comment]
I want to nest EditorJS, too. 
I developed editor-js-grid to resolve it. 

https://www.npmjs.com/package/editor-js-grid

But EditorJS can't be nested in EditorJS. 
Because operations don't work correctly.

**Comment by gohabereg** [comment]
https://github.com/codex-team/editor.js/pull/1055#issuecomment-664018031

**Comment by hata6502** [comment]
editor-js-grid is revived as editorjs-layout!
See: https://github.com/hata6502/editorjs-layout
